"""FCIP Extraction Prompts."""

from .extraction import (
    FORENSIC_ANALYST_SYSTEM,
    CLAIM_EXTRACTION_PROMPT,
    DOCUMENT_CLASSIFICATION_PROMPT,
    ENTITY_RESOLUTION_PROMPT,
    CONTRADICTION_ANALYSIS_PROMPT,
    ARGUMENT_GENERATION_PROMPT,
    get_prompt_hash,
)

__all__ = [
    "FORENSIC_ANALYST_SYSTEM",
    "CLAIM_EXTRACTION_PROMPT",
    "DOCUMENT_CLASSIFICATION_PROMPT",
    "ENTITY_RESOLUTION_PROMPT",
    "CONTRADICTION_ANALYSIS_PROMPT",
    "ARGUMENT_GENERATION_PROMPT",
    "get_prompt_hash",
]
